language: python
install:
    - git clone https://github.com/thinca/vim-themis && (cd vim-themis && git show HEAD)
    - pip install vim-vint
before_script:
    - uname -a
    - vim --version
script:
    - vint --warning $(git ls-files | grep -e '\.vim$' | grep -v vital) --color
    - ./vim-themis/bin/themis test/
